config/routes.rb
Rails.application.routes.draw do

  get 'favorites/index'
  devise_for :users
  root 'tops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :users, only: [:show, :edit, :update] do
		resources :favorites, only: [:index]  #お気に入り
	end

	namespace :admin do
    resources :users, only: [:index,:destroy]
    resources :shops, only: [:index,:destroy]
  	end

	resources :shops do
		resources :post_comments, only: [:create,:destroy] #コメント機能
		resource :favorites, only: [:create, :destroy]  #お気に入り
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
    belongs_to :shop

    validates :comment, presence: true

end

app/models/shop.rb
class Shop < ApplicationRecord
	def self.search(search)
      if search
        Shop.where(['address LIKE ?', "%#{search}%"])#titleの部分に検索したい部分一致のカラムを入れる
      else
        Shop.all.order(created_at: :desc)
      end
  end

  def within_box(distance, latitude, longitude)
        distance = distance
        center_point = [latitude, longitude]
        box = Geocoder::Calculations.bounding_box(center_point, distance)
        self.within_bounding_box(box)
  end

  geocoded_by :address       #GMAP
  after_validation :geocode, if: :address_changed?    #GMAP

	belongs_to :user
	attachment :shop_image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, foreign_key: 'shop_id', dependent: :destroy #お気に入り
  has_many :users, through: :favorites #お気に入り

  with_options presence: true do
    validates :shop_name
    validates :introduction
    validates :first_menu
    validates :first_price
    validates :second_menu
    validates :second_price
    validates :start_time
    validates :last_time
    validates :holiday
    validates :address
    validates :phone_number
  end

end

app/models/user.rb
class User < ApplicationRecord
	acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops, dependent: :destroy
  has_many :post_comments, dependent: :destroy #コメント機能
  has_many :favorites, through: :favorites, source: :shop #お気に入り,
    #has_many :favposts, through: :favorites, source: :shop #お気に入り


    validates :name, presence: true, uniqueness: true
    validates :email, uniqueness: true

  attachment :profile_image

end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
	before_action :admin_user
  def index
  	@shops = Shop.search(params[:search])
  end

  def destroy
    @shop = Shop.find(params[:id])
	  @shop.destroy
	  redirect_to admin_shops_path
  end

  private
    def shop_params
  			params.require(:shop).permit(:search)
  	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :admin_user

	def index
		@users = User.all.order(created_at: :asc)
	end

	def destroy
	    user = User.find(params[:id])
	    user.destroy
	    redirect_to admin_users_path
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
  	@favorites = Favorite.where(user_id: current_user)
    @user = current_user
  end

  def create
  	user = current_user
  	shop = Shop.find(params[:shop_id])
    Favorite.create(user_id:user.id,shop_id:shop.id)
    redirect_to user_favorites_path(current_user)
  end

  def destroy
  	user = current_user
  	shop = Shop.find(params[:shop_id])
    favorite = Favorite.find_by(user_id: user.id,shop_id:shop.id)
    favorite.destroy
    redirect_to user_favorites_path(current_user)
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
before_action :authenticate_user!
	def create
		shop = Shop.find(params[:shop_id])
	    comment = current_user.post_comments.new(post_comment_params)
	    comment.shop_id = shop.id
	    if comment.save
	       redirect_to shop_path(shop)
	    else
	       redirect_to shop_path(comment.shop)
	    end

	end

	def destroy
	  	post_comment = PostComment.find(params[:id])
		post_comment.destroy
		redirect_to shop_path(post_comment.shop)
  	end

	private

	def post_comment_params
	  params.require(:post_comment).permit(:user_id,
	                      :shop_id,
	                      :comment)
	end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  def index
  	@shops = Shop.search(params[:search]) #検索機能
    @user = current_user
  end

  def show
  	@shop = Shop.find(params[:id])
  	@post_comment = PostComment.new  #コメント機能
  	@favorite = Favorite.new #お気に入り
  end

  def search_location
        latitude = params[:latitude].to_f
        longitude = params[:longitude].to_f
        @locations = Shop.within_box(0.310686, latitude, longitude)
end

  def new
  	@shop = Shop.new
    @user = current_user
  end

  def create
  	@shop = Shop.new(shop_params)
  	@shop.user_id = current_user.id
    @shop.address = @shop.address.gsub(/\d+/, "").gsub(/\-+/, "") #GMAP
  	if @shop.save
  	   redirect_to shops_path
    else
       render :new
    end
  end

  def edit
  	@shop = Shop.find(params[:id])
  end

  def update
  	@shop = Shop.find(params[:id])
    if @shop.update(shop_params)
       redirect_to shop_path(@shop.id)
    else
       render :edit
    end
  end

  def destroy
  	@shop = Shop.find(params[:id])
	  @shop.destroy
	  redirect_to shops_path
  end

  private

  def shop_params
  			params.require(:shop).permit(:shop_name,
  										 :introduction,
  										 :first_menu,
  										 :first_price,
  										 :second_menu,
  										 :second_price,
  										 :start_time,
  										 :last_time,
  										 :holiday,
  										 :address,
  										 :phone_number,
  										 :shop_image,
  										 :user_id,
  										 :search
  										 )
  end



end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  	@user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	 @user = User.find(params[:id])
     @shops = Shop.where(user_id: params[:id])
  end

  def edit
  	 @user = User.find(params[:id])
  end


  def update
  	@user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end



  private
    def user_params
        params.require(:user).permit(:name, :profile_image)
    end

end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shops/index.html.erb
<sectin>
  <div class="search">
    <div class="form-inline">
    <%= form_tag(admin_shops_path, :method => 'get' ) do %>
      <%= text_field_tag :search,params[:search], class: "form-control shadow-sm",placeholder: "地域で検索　例：横浜" %>
      <%= submit_tag ' 検索 ', :address => nil %>
    <% end %>
    </div>
  </div>
	<table class="table">
  	 <thead>
      <tr>
	   <th>現在宣伝中のカフェ一覧</th>
	   <th></th>
     <th></th>
     <th></th>
      </tr>
  	 </thead>
  	 <tbody>

		<% @shops.each do |shop| %>
	<tr>
	  <td>
       <%= attachment_image_tag shop, :shop_image, size:'100x100',fallback: "no_image.png"%>
       <%= shop.shop_name %>
    </td>
    <td>
       <%= shop.address %>
    </td>
    <td>
       <%= shop.created_at %>
    </td>
	   <td><%= link_to "詳細", shop_path(shop.id), class: "btn btn-outline-primary" %>
         <%= link_to "消去" ,admin_shop_path(shop.id), method: :delete, "data-confirm" => "削除しますか?", class: "btn btn-outline-danger" %>
     </td>
    </tr>
    <% end %>
    </tbody>
 </table>
</sectin>

app/views/admin/users/index.html.erb
<sectin>
	<table class="table">
  	 <thead>
      <tr>
	   <th>会員一覧</th>
      </tr>
  	 </thead>
  	 <tbody>

		<% @users.each do |user| %>
	<tr>
	   <td>
       <%= attachment_image_tag user, :profile_image, size:'70x70', fallback: "no_image.png" %>
       <%= user.name %>
       <%= user.created_at %>
      </td>
	   <td><%= link_to "会員詳細", user_path(user.id), class: "btn btn-outline-primary" %>
         <%= link_to "ユーザー消去" ,admin_user_path(user.id), method: :delete, "data-confirm" => "削除しますか?", class: "btn btn-outline-danger" %>
     </td>
    </tr>
    <% end %>
    </tbody>
 </table>
</sectin>

app/views/favorites/index.html.erb
<h3 class="favorite-user-name"><%= @user.name %>さんのお気に入り</h3>
<div class="shops">
    <div class="container">
      <div class="row">
          <% @favorites.each do |favorite| %>
            <div class="col-lg-4 md-4"style="margin-bottom:50px;">
               <div class="card">
                <%= attachment_image_tag favorite.shop,:shop_image, size:"100x250",class: "card-img-top",fallback: "no_image.png" %>
                  <div class="card-body">
                   <p class="card-address"><i class="fas fa-map-marker-alt"></i><%= favorite.shop.address %></p>
                    <h5 class="card-title"><%= link_to shop_path(favorite.shop.id) do %><%= favorite.shop.shop_name %></h5>
                    <% end %>
                  <% if user_signed_in? %>
                    <%= link_to 'お気に入りを解除する', shop_favorites_path(favorite.shop.id), method: :delete, class: "btn-outline-success" %>
                  <% end %>
                  </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>

app/views/shops/edit.html.erb
<div class="forms">
  <div class="form-panel">
    <h2>店鋪内容を変更する</h2>
    <%= form_for(@shop) do |f| %>

      <div class="form-item">
        <%= f.label :店名 %><br />
        <%= f. text_field :shop_name %>
      </div>
      <div class="form-item">
        <%= f.label :店の説明 %><br />
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-item">
        <%= f.label :店の写真 %>
        <%= f.attachment_field :shop_image, placeholder: "ファイルを選択" %>
      </div>
      <div class="form-item">
        <%= f.label :住所 %><br />
        <%= f.text_field :address %>
      </div>
      <div class="form-item">
        <%= f.label :電話番号 %><br />
        <%= f.text_field :phone_number %>
      </div>
      <div class="form-item">
        <%= f.label :おすすめメニュー１ %><br />
        <%= f.text_field :first_menu %>
      </div>
      <div class="form-item">
        <%= f.label :おすすめメニュー１の価格 %><br />
        <%= f.text_field :first_price %>
      </div>
      <div class="form-item">
        <%= f.label :おすすめメニュー２ %><br />
        <%= f.text_field :second_menu %>
      </div>
      <div class="form-item">
        <%= f.label :おすすめメニュー２の価格 %><br />
        <%= f.text_field :second_price %>
      </div>
      <div class="form-item">
        <%= f.label :営業開始時間 %><br />
        <%= f.text_field :start_time %>
      </div>
      <div class="form-item">
        <%= f.label :営業終了時間 %><br />
        <%= f.text_field :last_time %>
      </div>
      <div class="form-item">
        <%= f.label :定休日 %><br />
        <%= f.text_field :holiday %>
      </div>

      <div class="button-panel">
        <%= f.submit "変更を保存" , class: "button-panel btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/index.html.erb
<div class="shop-index">
  <div class="search">
    <div class="form-inline">
    <%= form_tag(shops_path, :method => 'get' ) do %>
      <%= text_field_tag :search,params[:search], class: "form-control shadow-sm",placeholder: "地域で検索　例：横浜" %>
      <%= submit_tag ' 検索 ', :address => nil, class: "btn-success btn-lg rounded-circle p-1 shadow-sm" %>
    <% end %>
    </div>
  </div>
  <div class="shops">
    <div class="container">
      <div class="row">
          <% @shops.each do |shop| %>
            <div class="col-lg-4 md-4"style="margin-bottom:50px;">
               <div class="card">
                <%= attachment_image_tag shop, :shop_image, size:'100x250',class: "card-img-top",fallback: "no_image.png"%>
                  <div class="card-body">
                   <p class="card-address"><i class="fas fa-map-marker-alt"></i><%= shop.address %></p>
                    <p class="card-title"><%= link_to shop_path(shop.id) do %><%= shop.shop_name %></p>
                    <% end %>
                    <% if user_signed_in? %>
                    <% if !Favorite.exists?(user_id:current_user.id, shop_id:shop.id) %>
                    <%= link_to "お気に入り登録",shop_favorites_path(shop),method: :post,class: "btn-outline-warning" %>
                    <% else %>
                    <% end %>
                    <% end %>
                  </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shops/new.html.erb
<div class="forms">
  <div class="form-panel">
    <h2>自分の店を公開する</h2>
    <%= form_for(@shop) do |f| %>

      <div class="form-item">
        <%= f.label :店名 %><br />
        <%= f. text_field :shop_name %>
      </div>
      <div class="form-item">
        <%= f.label :店の説明 %><br />
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-item">
        <%= f.label :店の写真 %>
        <%= f.attachment_field :shop_image, placeholder: "ファイルを選択" %>
      </div>
      <div class="form-item">
        <%= f.label :住所 %><br />
        <%= f.text_field :address %>
      </div>
      <div class="form-item">
        <%= f.label :電話番号 %><br />
        <%= f.text_field :phone_number %>
      </div>
      <div class="form-item">
        <%= f.label :おすすめメニュー１ %><br />
        <%= f.text_field :first_menu %>
      </div>
      <div class="form-item">
        <%= f.label :おすすめメニュー１の価格 %><br />
        <%= f.text_field :first_price %>
      </div>
      <div class="form-item">
        <%= f.label :おすすめメニュー２ %><br />
        <%= f.text_field :second_menu %>
      </div>
      <div class="form-item">
        <%= f.label :おすすめメニュー２の価格 %><br />
        <%= f.text_field :second_price %>
      </div>
      <div class="form-item">
        <%= f.label :営業開始時間 %><br />
        <%= f.text_field :start_time %>
      </div>
      <div class="form-item">
        <%= f.label :営業終了時間 %><br />
        <%= f.text_field :last_time %>
      </div>
      <div class="form-item">
        <%= f.label :定休日 %><br />
        <%= f.text_field :holiday %>
      </div>

      <div class="button-panel">
        <%= f.submit "送信" , onclick: "getPosition();",class: "button-panel btn-danger" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/show.html.erb
<div class="shop-info">
  	<div class="shop-image">
  		<%= attachment_image_tag @shop, :shop_image, size:'200x300',class: "card-img-top",fallback: "no_image.png"%>
        <table class="custom_tb">
          <tbody>
            <tr>
              <th>住所</th>
              <td><%= @shop.address %></td>
            </tr>
            <tr>
              <th>電話番号</th>
              <td><%= @shop.phone_number %></td>
            </tr>
          </tbody>
        </table>
<!---GMAPAPI------------------>
        <div id="shop-map"></div>
<!---GMAPAPI------------------>
  	</div>
    <div class="text-column">
      	<div class="shop-title"><%= @shop.shop_name %></div>
      	<div class="shop-introduction"><%= @shop.introduction %></div>
      <p><i class="far fa-check-circle"></i></i>おすすめメニュー</p>
      	<div class="menu">
          <div class="menu-title"><%= @shop.first_menu %></div>
          <div class="price"><%= @shop.first_price %>円(税抜き)</div>
        </div>
      	<div class="menu">
          <div class="menu-title"><%= @shop.second_menu %></div>
          <div class="price"><%= @shop.second_price %>円(税抜き)</div>
        </div>
        <p><i class="far fa-check-circle"></i></i>営業時間</p>
        <div class="business-time"><%= @shop.start_time %> ~ <%= @shop.last_time %></div>
        <p><i class="far fa-check-circle"></i></i>定休日</p>
        <div class="holiday"><%= @shop.holiday %></div>
        <div class="favorite-button">
          <% if user_signed_in? %>
             <% if !Favorite.exists?(user_id:current_user.id, shop_id:@shop.id) %>
                <%= link_to "お気に入り登録",shop_favorites_path(@shop),method: :post,class: "btn-warning" %>
             <% else %>
            <% end %>
          <% end %>
        </div>
    </div>
</div>
<div class="comment">

  <%= form_for [@shop, @post_comment] do |f| %>
      <div class="row">
          <div class="col-sm-12">
              <%= f.text_field :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
          </div>
      </div>
      <%= f.submit "コメント送信", class: "btn btn-secondary" %>
  <% end %>

  <div class="line-bc">
    <% @shop.post_comments.each do |post_comment| %>
     		<li class="comment">
              <div class="comment-body bb">
                  <div class="comment-text">
                      <div class="comment-author clearfix">
                          <%= post_comment.user.name %>さん
                          <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
                      </div>
                      <div class="balloon6">
                      	<div class="chatting">
                            	<div class="faceicon">
                               <%= attachment_image_tag post_comment.user, :profile_image, fallback: "no_image.jpg" %>
                            	</div>
          					　　　　　<div class="says">
                        		  <%= post_comment.comment %>
                        		</div>
                        		<% if user_signed_in? && current_user.id == post_comment.user_id%>
                        		<%= link_to "削除", shop_post_comment_path(@shop,post_comment.id), method: :delete, "data-confirm" => "本当に削除してよろしいのですか?" %>
                            <% elsif user_signed_in? && current_user.admin %>
                            <%= link_to "削除", shop_post_comment_path(@shop,post_comment.id), method: :delete, "data-confirm" => "本当に削除してよろしいのですか?" %>
                        		<% end %>
                      	</div>
                      </div>
                  </div>
              </div>
          </li>
      <% end %>
  </div>
</div>

<script type="text/javascript">
    function initMap(){
      const myLatLng = {lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %>}; //変数をここで定義
      let map = new google.maps.Map(document.getElementById('shop-map'),{
        center: myLatLng,
        zoom: 15
      });
      var marker = new google.maps.Marker({   //マーカーをつける
          position: myLatLng,
          map: map
      });
    }

</script>
<script src="//maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_KEY']%>&callback=initMap"></script>

app/views/tops/index.html.erb
<div class="container-fluid">
	  <div class= "row">
		<div class="carousel slide carousel-fade" data-ride="carousel">
		   <div class="carousel-inner">
			    <div class="carousel-item active">
			    	<div class="logo">
				    	<h3>Cafenavi</h3><br>
				    	<h1>KOMINKA</h1>
			    	</div>
			    	<div class="index-button">
			    	<%= link_to "古民家カフェを探す", shops_path, class: "btn btn-warning rounded-pill btn-lg" %>
			    	</div>
			      <%= image_tag("photo1.jpg",:size =>'1280x520') %>
			    </div>
			    <div class="carousel-item">
			    	<div class="logo">
				    	<h3>Cafenavi</h3><br>
				    	<h1>KOMINKA</h1>
			    	</div>
			    	<div class="index-button">
			    	<%= link_to "古民家カフェを探す", shops_path, class: "btn btn-warning rounded-pill btn-lg" %>
			    	</div>
			     <%= image_tag("photo2.jpg", :size =>'1280x520') %>
			    </div>
			    <div class="carousel-item">
			    	<div class="logo">
				    	<h3>Cafenavi</h3><br>
				    	<h1>KOMINKA</h1>
			    	</div>
			    	<div class="index-button">
			    	<%= link_to "古民家カフェを探す", shops_path, class: "btn btn-warning rounded-pill btn-lg" %>
			    	</div>
			      <%= image_tag("photo4.jpg", :size =>'1280x520') %>
		    </div>
		  </div>
		</div>
	  </div>
</div>
<div class="about">
	<div class="about-title">
		<h2>Cafenavi  KOMINKAについて</h2>
		<div class="introduction">
			<p>「古民家」とは、建築年数がかなり経過した日本の民家です。伝統的な日本の家とも言われています。<br>
				古民家は、材木の組み合わせと土壁で構成された建築物のため、再生が簡単にできるという強みがあり、古い部分を新しいものと取り替える、間取りを変更するなど、実は柔軟にできる構造の建物です。<br>
				そのため、店鋪として再利用されることが多くなってます。<br>
				このサイトは、穏やかな時間を過ごしたい、懐かしさを感じたい、日本の伝統に触れたいという方達が簡単に古民家カフェを探せるだけでなく、日本の伝統建築でカフェの経営を始めた方たちの宣伝のために使うことができます。
			</p>
		</div>
	</div>
</div>
<div class="photo-panel">
	<div class="photo">
		<div class= "row">
			<div class="col-ld-4 md-3"><%= image_tag("photo3.jpg") %></div>
			<div class="col-ld-4 md-3"><%= image_tag("photo6.jpg") %></div>
			<div class="col-ld-4 md-3"><%= image_tag("photo7.jpg") %></div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<section class="userinfo text-center">
  <div class="info-panel">
	　<h2>会員情報変更</h2>
 		<%= form_for(@user) do |f| %>
		　<div class="namelabel">
       	 	<label for="name">名前変更</label>
        	<%= f.text_field :name, class: "name", autofocus: true %>
   		  </div>

    	<div class="imagelabel">
    		<%= attachment_image_tag @user, :profile_image, size:'100x100',fallback: "no_image.png" %>
     		<label class="control-label sr-only">プロフィール画像変更</label>
    		<%= f.attachment_field :profile_image, class: "user_image", placeholder: "ファイルを選択" %>
    	</div><br>

    	<div class="introductionlabel">
        <% if @user.errors.any? %>
          <div id="error_explanation">
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                 <li>Error！！<%= message %></li>
                <% end %>
              </ul>
          </div>
        <% end %>
      </div>
         <%= f.submit "情報を変更する",class: "btn btn-outline-secondary active" %>
		<% end %>
  </div>
  <%= link_to "退会する" ,user_registration_path(id: current_user.id), method: :delete, "data-confirm" => "退会しますか？", class: "btn btn-danger" %>
</section>

app/views/users/show.html.erb
<!---ユーザーの投稿一覧-->
<div class="user-post">
  <div class="imagelabel text-center">
      <%= attachment_image_tag @user, :profile_image, size:'100x100',fallback: "no_image.png" %>
      <h3><%= @user.name %>さん</h3><%= link_to "プロフィール変更", edit_user_path(current_user),class: "btn btn-primary" %>
  </div>
  <div class="shop-index">
    <h3 class="column-title">宣伝中のカフェ</h3>
    <div class="shops">
      <div class="container">
        <div class="row">
            <% @shops.each do |shop| %>
              <div class="col-lg-4 md-4"style="margin-bottom:50px;">
                 <div class="card">
                  <%= attachment_image_tag shop, :shop_image, size:'100x250',fallback: "no_image.png",class: "card-img-top" %>
                    <div class="card-body">
                     <p class="card-address"><i class="fas fa-map-marker-alt"></i><%= shop.address %></p>
                      <h5 class="card-title"><%= link_to shop_path(shop.id) do %><%= shop.shop_name %></h5>
                      <% end %>
                        <% if  current_user %>
                          <%= link_to "編集",edit_shop_path(shop.id), class: "btn btn-outline-success" %>
                          <%= link_to "削除", shop_path(shop.id), class: "btn btn-outline-danger", method: :delete, "data-confirm" => "本当に削除してよろしいのですか?" %>
                      <% end %>
                    </div>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>