config/routes.rb
Rails.application.routes.draw do

  get 'favorites/index'
  devise_for :users
  root 'tops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :users, only: [:show, :edit, :update] do
		resources :favorites, only: [:index]  #お気に入り
	end

	namespace :admin do
    resources :users, only: [:index,:destroy]
    resources :shops, only: [:index,:destroy]
  	end

	resources :shops do
		resources :post_comments, only: [:create,:destroy] #コメント機能
		resource :favorites, only: [:create, :destroy]  #お気に入り
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
    belongs_to :shop

    validates :comment, presence: true

end

app/models/shop.rb
class Shop < ApplicationRecord
	def self.search(search)
      if search
        Shop.where(['address LIKE ?', "%#{search}%"])#titleの部分に検索したい部分一致のカラムを入れる
      else
        Shop.all.order(created_at: :desc)
      end
  end

  def within_box(distance, latitude, longitude)
        distance = distance
        center_point = [latitude, longitude]
        box = Geocoder::Calculations.bounding_box(center_point, distance)
        self.within_bounding_box(box)
  end

  geocoded_by :address       #GMAP
  after_validation :geocode, if: :address_changed?    #GMAP

	belongs_to :user
	attachment :shop_image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, foreign_key: 'shop_id', dependent: :destroy #お気に入り
  has_many :users, through: :favorites #お気に入り

  with_options presence: true do
    validates :shop_name
    validates :introduction
    validates :first_menu
    validates :first_price
    validates :second_menu
    validates :second_price
    validates :start_time
    validates :last_time
    validates :holiday
    validates :address
    validates :phone_number
  end

end

app/models/user.rb
class User < ApplicationRecord
	acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops, dependent: :destroy
  has_many :post_comments, dependent: :destroy #コメント機能
  has_many :favorites, through: :favorites, source: :shop #お気に入り,
    #has_many :favposts, through: :favorites, source: :shop #お気に入り


    validates :name, presence: true, uniqueness: true
    validates :email, uniqueness: true

  attachment :profile_image

end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
	before_action :admin_user
  def index
  	@shops = Shop.search(params[:search])
  end

  def destroy
    @shop = Shop.find(params[:id])
	  @shop.destroy
	  redirect_to admin_shops_path
  end

  private
    def shop_params
  			params.require(:shop).permit(:search)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
  	@favorites = Favorite.where(user_id: current_user)
    @user = current_user
  end

  def create
  	user = current_user
  	shop = Shop.find(params[:shop_id])
    Favorite.create(user_id:user.id,shop_id:shop.id)
    redirect_to user_favorites_path(current_user)
  end

  def destroy
  	user = current_user
  	shop = Shop.find(params[:shop_id])
    favorite = Favorite.find_by(user_id: user.id,shop_id:shop.id)
    favorite.destroy
    redirect_to user_favorites_path(current_user)
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
before_action :authenticate_user!
	def create
		shop = Shop.find(params[:shop_id])
	    comment = current_user.post_comments.new(post_comment_params)
	    comment.shop_id = shop.id
	    if comment.save
	       redirect_to shop_path(shop)
	    else
	       redirect_to shop_path(comment.shop)
	    end

	end

	def destroy
	  	post_comment = PostComment.find(params[:id])
		post_comment.destroy
		redirect_to shop_path(post_comment.shop)
  	end

	private

	def post_comment_params
	  params.require(:post_comment).permit(:user_id,
	                      :shop_id,
	                      :comment)
	end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  def index
  	@shops = Shop.search(params[:search]) #検索機能
    @user = current_user
  end

  def show
  	@shop = Shop.find(params[:id])
  	@post_comment = PostComment.new  #コメント機能
  	@favorite = Favorite.new #お気に入り
  end

  def search_location
        latitude = params[:latitude].to_f
        longitude = params[:longitude].to_f
        @locations = Shop.within_box(0.310686, latitude, longitude)
end

  def new
  	@shop = Shop.new
    @user = current_user
  end

  def create
  	@shop = Shop.new(shop_params)
  	@shop.user_id = current_user.id
    @shop.address = @shop.address.gsub(/\d+/, "").gsub(/\-+/, "") #GMAP
  	if @shop.save
  	   redirect_to shops_path
    else
       render :new
    end
  end

  def edit
  	@shop = Shop.find(params[:id])
  end

  def update
  	@shop = Shop.find(params[:id])
    if @shop.update(shop_params)
       redirect_to shop_path(@shop.id)
    else
       render :edit
    end
  end

  def destroy
  	@shop = Shop.find(params[:id])
	  @shop.destroy
	  redirect_to shops_path
  end

  private

  def shop_params
  			params.require(:shop).permit(:shop_name,
  										 :introduction,
  										 :first_menu,
  										 :first_price,
  										 :second_menu,
  										 :second_price,
  										 :start_time,
  										 :last_time,
  										 :holiday,
  										 :address,
  										 :phone_number,
  										 :shop_image,
  										 :user_id,
  										 :search
  										 )
  end



end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  	@user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	 @user = User.find(params[:id])
     @shops = Shop.where(user_id: params[:id])
  end

  def edit
  	 @user = User.find(params[:id])
  end


  def update
  	@user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end



  private
    def user_params
        params.require(:user).permit(:name, :profile_image)
    end

end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafenavikominka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://use.fontawesome.com/releases/v5.9.0/css/all.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <div class="u-header">
        <p class="u-header-text">古民家カフェ専門の検索・宣伝サイト　｜　Cafenavi KOMINKA</p>
      </div>
      
      <div class="main-menu">
        <nav>
          <ul>
            <li class="f-left"><%= link_to image_tag("logo.png",:size =>'200x30'), root_path, title: "トップに戻る" %></li>
            <% if user_signed_in? %>
                <li>
                  <%= link_to "カフェを探す", shops_path %>
                </li>
                <li>
                  <%= link_to "お気に入り", user_favorites_path(current_user) %></li>
                <li>
                  <%= link_to '宣伝中のカフェ', user_path(current_user.id) %></li>
                <li>
                  <%= link_to "宣伝する", new_shop_path %>
                </li>
            <% if current_user.admin == true %>
                   <li>
                    <%= link_to '会員一覧', admin_users_path %>
                   </li>
                  <li>
                    <%= link_to "カフェ一覧", admin_shops_path %>
                  </li>
                <% end %>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                  </li>
            <% else %>
                <li>
                  <%= link_to "カフェを探す", shops_path %>
                </li>
                <li>
                  <%= link_to "新規会員登録", new_user_registration_path %>
                </li>
                <li>
                  <%= link_to "ログイン",new_user_session_path %>
                </li>
            <% end %>
          </ul>
        </nav>
      </div>
<!-----ハンバーガーボタン------------->
      <div class="zdo_drawer_menu">
           <div class="zdo_drawer_bg"></div>
            <button type="button" class="zdo_drawer_button">
              <span class="zdo_drawer_bar zdo_drawer_bar1"></span>
              <span class="zdo_drawer_bar zdo_drawer_bar2"></span>
              <span class="zdo_drawer_bar zdo_drawer_bar3"></span>
             <!--<span class="zdo_drawer_menu_text zdo_drawer_text">MENU</span>-->
              <span class="zdo_drawer_close zdo_drawer_text">CLOSE</span>
            </button>
            <nav class="zdo_drawer_nav_wrapper">
              <ul class="zdo_drawer_nav">
                <% if user_signed_in? %>
                  <li>
                    <%= link_to "カフェを探す", shops_path %>
                  </li>
                  <li>
                    <%= link_to "お気に入り", user_favorites_path(current_user) %></li>
                  <li>
                    <%= link_to '宣伝中のカフェ', user_path(current_user.id) %></li>
                  <li>
                    <%= link_to "宣伝する", new_shop_path %>
                  </li>
                <% if current_user.admin == true %>
                     <li>
                      <%= link_to '会員一覧', admin_users_path %>
                     </li>
                    <li>
                      <%= link_to "カフェ一覧", admin_shops_path %>
                    </li>
                  <% end %>
                  <li>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                    </li>
                <% else %>
                  <li>
                    <%= link_to "カフェを探す", shops_path %>
                  </li>
                  <li>
                    <%= link_to "新規会員登録", new_user_registration_path %>
                  </li>
                  <li>
                    <%= link_to "ログイン",new_user_session_path %>
                  </li>
              <% end %>
              </ul>
            </nav>
      </div>
<!---------------->
    </header>
    <div class="header-padding"></div>
    <%= yield %>
    <footer>
        <p class="footer-text">Cafenavi KOMINKA</p>
      </div>
    </footer>
  </body>
</html>